version: '3.8'
services: 
  database:
    image: mongo
    restart: always 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=stac
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes: 
      - mongo_data:/data/db 
    ports:
      - 27017:27017
  
volumes: 
  mongo_data: 