name: go-stac-api mongo backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    services:
      mongo_db_service:
        image: mongo:3.6
        env:
          MONGO_INITDB_ROOT_USERNAME: stac
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Run
        run: go run main.go
        env:
          MONGOURI: mongodb://stac:root@database:27017
          MONGOLOCAL: mongodb://stac:root@localhost:27017
        ports:
          - 6001:6001

      - name: Test
        run: go test -v ./...